# Generated by Django 4.1.7 on 2023-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_stepmedia_delete_stepimage'),
        ('accounts', '0005_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='customers', to='recipes.recipe'),
        ),
    ]
