# Generated by Django 4.1.7 on 2023-04-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_commentmedia_delete_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.comment'),
        ),
        migrations.AlterField(
            model_name='recipemedia',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipe'),
        ),
    ]
