# Generated by Django 4.1.7 on 2023-04-04 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_commentmedia_comment_alter_recipemedia_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='step_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpeg', 'jpg', 'png'])])),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.step')),
            ],
        ),
        migrations.DeleteModel(
            name='StepImage',
        ),
    ]
